services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-nlw
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - nlw-network

networks:
  nlw-network:
    driver: bridge

volumes:
  postgres-data: